version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s - %(thread)d - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: $ConsoleLogLevel
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: $LogFileDir/$FileName
    maxBytes: $FileSize
    backupCount: $MaxCount
    delay: true
    level: $FileLogLevel
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
      - file
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - default
      - file
    propagate: no
root:
  level: DEBUG
  handlers:
    - default
    - file