# Copyright 2024 Broadcom. All Rights Reserved.

CONTROLS = "controls"
AUTH_CONTEXT = "auth_context"
CONTROL = "control"
PRODUCT = "product"
DRIFT_VALUES = "drift_values"
COMPLIANCE_VALUES = "compliance_value"
TEST_RESULT_FILE = "test_result.txt"
CONFIGURATION_ID = "configuration_id"
MONITORING_POLICY = "monitoring_policy"
COMPLIANCE_CONFIG = "compliance_config"
CONTROL_MODULES_CONTROLS = "functional_tests/central_test/controls"
CONTROL_COMPLIANCE_TEMPLATE = "control_compliance_template.json"
HOST_NAME = "host_name"
JSON_PATH = "json_path"
REMEDIATION = "remediation"

CHECK_COMPLIANCE = "check_compliance"

REMOTE = "remote"
STATUS = "status"
RESULT = "result"
CURRENT = "current"
FAIL = "FAIL"
PASS = "PASS"
OVERRIDES = "__OVERRIDES__"
ROLLBACK = "rollback"
VALUE = "value"
TEST_TARGET = "test_target"
SSH_CREDENTIAL = "ssh_credential"
